[build]
  publish = "dist"
  command = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "#custom"
  command = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  functionsPort = 9999
